[2025-04-16T19:19:00.698+0000] {processor.py:186} INFO - Started process (PID=292) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:00.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:19:00.701+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:19:00.700+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:02.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:02.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.305 seconds
[2025-04-16T19:19:16.573+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:16.574+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:19:16.577+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:19:16.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:16.614+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:19:16.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/ETL/WeatherETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL/WeatherETL.py", line 18
    return pg_hook = PostgresHook(postgres_conn_id="MY_DB")
                   ^
SyntaxError: invalid syntax
[2025-04-16T19:19:16.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:16.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.100 seconds
[2025-04-16T19:19:22.466+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:22.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:19:22.469+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:19:22.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:24.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:24.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.257 seconds
[2025-04-16T19:19:54.964+0000] {processor.py:186} INFO - Started process (PID=343) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:54.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:19:54.968+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:19:54.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:57.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:19:57.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.267 seconds
[2025-04-16T19:20:03.424+0000] {processor.py:186} INFO - Started process (PID=345) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:20:03.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:20:03.427+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:20:03.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:20:05.640+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:20:05.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.277 seconds
[2025-04-16T19:20:35.997+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:20:35.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:20:36.003+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:20:36.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:20:38.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:20:38.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.472 seconds
[2025-04-16T19:21:09.091+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:09.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:21:09.095+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:21:09.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:11.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:11.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.317 seconds
[2025-04-16T19:21:25.222+0000] {processor.py:186} INFO - Started process (PID=420) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:25.223+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:21:25.225+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:21:25.225+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:27.416+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:27.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.236 seconds
[2025-04-16T19:21:30.655+0000] {processor.py:186} INFO - Started process (PID=422) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:30.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:21:30.659+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:21:30.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:32.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:21:32.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.253 seconds
[2025-04-16T19:22:03.018+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:03.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:22:03.021+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:22:03.021+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:05.223+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:05.256+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 2.243 seconds
[2025-04-16T19:22:34.058+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:34.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:22:34.061+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:22:34.061+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:34.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:34.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.444 seconds
[2025-04-16T19:22:51.073+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:51.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:22:51.078+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:22:51.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:51.649+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:51.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.634 seconds
[2025-04-16T19:22:59.621+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:59.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:22:59.623+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:22:59.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:59.652+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:22:59.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/ETL/WeatherETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL/WeatherETL.py", line 38
    with DAG(
            ^
SyntaxError: '(' was never closed
[2025-04-16T19:22:59.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:22:59.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.100 seconds
[2025-04-16T19:23:22.619+0000] {processor.py:186} INFO - Started process (PID=507) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:23:22.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:23:22.623+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:23:22.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:23:23.071+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:23:23.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/ETL/WeatherETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL/WeatherETL.py", line 47, in <module>
    python_callable=read_fs
                    ^^^^^^^
NameError: name 'read_fs' is not defined
[2025-04-16T19:23:23.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:23:23.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.532 seconds
[2025-04-16T19:23:39.672+0000] {processor.py:186} INFO - Started process (PID=532) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:23:39.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:23:39.675+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:23:39.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:23:40.070+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:23:40.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/ETL/WeatherETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL/WeatherETL.py", line 39, in <module>
    dag_id=f'{dagName}',  # Name of the DAG
              ^^^^^^^
NameError: name 'dagName' is not defined
[2025-04-16T19:23:40.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:23:40.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.477 seconds
[2025-04-16T19:24:00.832+0000] {processor.py:186} INFO - Started process (PID=551) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:24:00.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:24:00.836+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:24:00.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:24:01.267+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:24:01.259+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/ETL/WeatherETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL/WeatherETL.py", line 47, in <module>
    python_callable=read_fs
                    ^^^^^^^
NameError: name 'read_fs' is not defined
[2025-04-16T19:24:01.272+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:24:01.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.508 seconds
[2025-04-16T19:24:05.509+0000] {processor.py:186} INFO - Started process (PID=553) to work on /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:24:05.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/ETL/WeatherETL.py for tasks to queue
[2025-04-16T19:24:05.518+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:24:05.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:24:05.973+0000] {logging_mixin.py:190} INFO - [2025-04-16T19:24:05.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/ETL/WeatherETL.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL/WeatherETL.py", line 47, in <module>
    python_callable=read_fs
                    ^^^^^^^
NameError: name 'read_fs' is not defined
[2025-04-16T19:24:05.977+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL/WeatherETL.py
[2025-04-16T19:24:06.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/ETL/WeatherETL.py took 0.555 seconds
